### PR TITLE
Clarify invalid offset and backtracking

### LINKED ISSUE #52: Can server skip ahead?
Can server skip ahead using Offset Retrieving Procedure? Current thinking is there is no harm in allowing it.

### PR DESCRIPTION
**Pull request by guoye-zhang**
Resolves #52 and #53

### CODE REVIEW

**Review by smatsson — COMMENTED** [review]
Is there an example use case for when the server returns a larger value than what has been sent by the client?

**Comment by guoye-zhang** [comment]
This was brought up by @gregw on the mailing list. I can't think of a use case, but I don't see much harm in allowing it either. We can definitely revisit this if you think it adds complexity to the client, or if there are any other reasons. What does a typical tus-v1 client do in this situation?

**Comment by smatsson** [comment]
I can't 100% guarantee it but I would think that the tus 1.0 client would just continue from the offset provided by the server. I don't see any harm in allowibg it but I'm just wondering when this could happen and for what reason. If the client sends 100 bytes and the server returns an offset of 200 something has obviously gone very wrong and the file is most likely corrupt or at the very least not safe to resume.

**Comment by Acconut** [comment]
> What does a typical tus-v1 client do in this situation?

I answered a bit in https://github.com/tus/tus-v2/issues/52#issuecomment-1189134243, but can elaborate a bit more here: In tus v1 it is not intended that the server skips forward (i think it is not explicitly mentioned but implicitly not allowed). As such, clients may rely on on this property in their implementation. For example, tus-js-client could handle forward jumps for uploads from disk files, but it currently does not support it when uploading from a streaming data source, e.g. a live webcam video. It may or may not error out (haven't test that yet), but I would assume it breaks.

General, I prefer simplicity when looking at the Upload-Offset header: I think it should only ever increase and only by the amount that the server receives from the client, i.e. not seeks backwards and not jumps forward. This allows clients to be keep simpler.

**Comment by guoye-zhang** [comment]
I also don't find a compelling use case for going forward. Yes, skipping ahead in dynamically generated content would be surprising. I think we can reword it so that the client is free to reject these offsets to simplify the implementation.

**Comment by Acconut** [comment]
> I think we can reword it so that the client is free to reject these offsets to simplify the implementation.

Let's do this. If servers want to skip ahead for some reason in the future, then clients should already be able to handle it or have explicit logic to error out.

**Review by Acconut — APPROVED** [review]

**Pull request merged**
